### ISSUE TITLE
unexpected exception thrown during HunterCollector loop & missing readme file?

### ISSUE THREAD

**Issue by seanmcfeely** [ace-ecosystem/ACE#101]
from hunter logs: `[__init__.py:971] [Collector] [1147] [ERROR] - unexpected exception thrown during loop for <saq.collectors.hunter.HunterCollector object at 0x7fa2e276d6d8>: 'NoneType' object has no attribute 'check_rules'`

error report:

```
data/error_reports/2020-07-18:17:28:06.402596
EXCEPTION
'NoneType' object has no attribute 'check_rules'
 
STACK TRACE
Traceback (most recent call last):
  File "/opt/ace/saq/collectors/__init__.py", line 969, in loop
    self.execute()
  File "/opt/ace/saq/collectors/__init__.py", line 1003, in execute
    tuning_matches = self.submission_filter.get_tuning_matches(next_submission)
  File "/opt/ace/saq/submission/__init__.py", line 340, in get_tuning_matches
    self.update_rules()
  File "/opt/ace/saq/submission/__init__.py", line 334, in update_rules
    need_update = self.tracking_scanner.check_rules()
AttributeError: 'NoneType' object has no attribute 'check_rules'
```

Which led me here and to notice that this referenced README is missing from the project repo.
https://github.com/ace-ecosystem/ACE/blob/7890615b4a40ce3454fc942480efa19de6491939/saq/collectors/__init__.py#L676

I noticed these tuning rules appear to be loaded out of whatever is specified in `collection.tuning_dir_*`,  but I don't have that. I do have a `collection.tuning_temp_dir` from the default config.

This doesn't appear to be causing us any issues.

**Comment by seanmcfeely** [comment]
I was just looking for something different and found the documentation on [submission filters](https://ace-ecosystem.github.io/ACE/admin/submission_filter/).

I can take ownership of fixing this next week when I come back to using the hunting service.

**Comment by unixfreak0037** [comment]
This was fixed [here](https://github.com/ace-ecosystem/ACE/commit/1cec98a5afd63befda1bddec971bdb3c03e915d7).
