### ISSUE TITLE
How to correctly set the timezone for query based hunters?

### ISSUE THREAD

**Issue by seanmcfeely** [ace-ecosystem/ACE#102]
By default the hunting service queries instances with timezones set to UTC. For our situation, this causes the splunk hunter to  look for events indexed in the future.

I started to modify the SplunkHunt to convert search times into a configured timezone but after looking it appears this may belong in the QueryHunt for consistent search time updates in the hunt database?

Is a config item needed to specify the timezone query based hunters should use? If so where does it make the most sense to introduce a configured timezone?

Thanks

**Comment by unixfreak0037** [comment]
There is now a [timezone field](https://github.com/ace-ecosystem/ACE/blob/dev/saq/collectors/splunk_hunter.py#L34) in the splunk hunter config.

We encountered this error too but we solved it by changing the timezone of the splunk account we are using to UTC.
