### ISSUE TITLE
Handle analysis modules that never return.

### ISSUE THREAD

**Issue by unixfreak0037** [ace-ecosystem/ACE#109]
We do a lot of really crazy analysis. Some times things go wrong and something either ends up in an infinite loop or stuck processing something that's going to take so long it's never going to return.

Need to be able to handle that from ACE. There is a timeout but it may not be working the way it's current designed.

**Comment by seanmcfeely** [comment]
@unixfreak0037 I've run the code at https://github.com/ace-ecosystem/ACE/commit/4c5362726914aedda580d49c6379817b188c558b against 25% of our workload in QA for ~12 hours and it's solved the problem for me.

look at this comparison instead of that commit that I've since updated: https://github.com/ace-ecosystem/ACE/compare/analysis-module-signaltimeout

**Comment by seanmcfeely** [comment]
look at this comparison instead of that commit that I've since updated: https://github.com/ace-ecosystem/ACE/compare/analysis-module-signaltimeout

**Comment by unixfreak0037** [comment]
@seanmcfeely I like this idea but read this [blog post](https://anonbadger.wordpress.com/2018/12/15/python-signal-handlers-and-exceptions/). I think that can end up leading to some weird bugs that will be difficult to root-cause.

Really, the best way to handle a runaway analysis (where the CPU is buried) is to just kill the process and let ACE restart analysis, skipping the failed module. I'm already starting to work on that for other reasons (like when olevba causes the entire process to exit), which we could use to solve this as well.

**Comment by seanmcfeely** [comment]
Ah, yea signals definitely shouldn't be used like this. I see how purposely catching signals like this could get ugly because of how python adds signal handlers to the call stack.

Awesome, I look forward to your code to handle these situations.

**Comment by unixfreak0037** [comment]
This has been resolved.
