### ISSUE TITLE
GUI - Sort alerts by detection count?

### ISSUE THREAD

**Issue by seanmcfeely** [ace-ecosystem/ACE#112]
On the alerts page, it would be nice and interesting to sort alerts by their detection counts.

- from most to least
- from least to most

Currently detection count is only displayed in parentheses:

![image](https://user-images.githubusercontent.com/3869452/89707432-d77fdb80-d93b-11ea-9851-9d003b34e4d3.png)

**Comment by unixfreak0037** [comment]
We would just need to make it a column instead of part of the description, then add the JS to support that.

**Comment by seanmcfeely** [comment]
I don't think I want this to be a column and I'm not going to spend time on this right now.
