### ISSUE TITLE
SLA functionality missing

### ISSUE THREAD

**Issue by seanmcfeely** [ace-ecosystem/ACE#128]
It appears that the SLA functionally was not implemented with the new version of GUI alert filters. We would like to have this back as it's nice for making sure alerts are not forgotten about when an analyst goes on vacation, etc.

old code:

```python
    # we want to display alerts that are either approaching or exceeding SLA
    sla_ids = [] # list of alert IDs that need to be displayed
    if saq.GLOBAL_SLA_SETTINGS.enabled or any([s.enabled for s in saq.OTHER_SLA_SETTINGS]):
        _query = db.session.query(GUIAlert).filter(GUIAlert.disposition == None)
        for alert_type in saq.EXCLUDED_SLA_ALERT_TYPES:
            _query = _query.filter(GUIAlert.alert_type != alert_type)
        for alert in _query:
            if alert.is_over_sla or alert.is_approaching_sla:
                sla_ids.append(alert.id)

    logging.debug("{} alerts in breach of SLA".format(len(sla_ids)))
```

Then, if an alert was approaching SLA it would trigger the default filters to be changed, such that, alert ownership is removed and ever analyst then sees all open (disposition == None) alerts, when they reset their filters. Also, alerts approaching SLA were highlighted in yellow and alerts over SLA were highlighted in red.

**Comment by unixfreak0037** [comment]
Sorry. If we had testing for the gui I would not have let that one through without addressing it.

**Comment by seanmcfeely** [comment]
No worries, I didn't think to test it either. I just noticed it wasn't working yesterday.
