### ISSUE TITLE
SSL issue during ACE install for devices with FQDN different from `hostname` command

### ISSUE THREAD

**Issue by krayzpipes** [ace-ecosystem/ACE#26]
During install, the certificate is populated with the following in `ssl/installer/install_ssl_certs.sh`

- `localhost`
- `$(hostname)`
- `127.0.0.1`

The node location (API PREFIX) is populated in `lib/saq/__init__.py` with `API_PREFIX = socket.getfqdn()`.

If the server--for example an EC2 instance like `ip-10.10.10.10.ec2.internal`-- has a hostname (`ip-10.10.10.10`) that is different than the FQDN (`ip-10.10.10.10.ec2.internal`), this will cause errors during manual submissions.

I recommend adding DNS.3 with $(hostname -f) as the value to the ssl install script.

**Comment by unixfreak0037** [comment]
Great idea there.

**Comment by krayzpipes** [comment]
Pull request waiting for review. Ended up just adding `$(hostname -f) as the second alternative name as the FQDN should be the only thing stored in `location` (API_PREFIX) within the `ace.nodes` table after the default install.
