### ISSUE TITLE
Add more descriptive error when storing an encrypted password for an integration that is not enabled.

### ISSUE THREAD

**Issue by krayzpipes** [ace-ecosystem/ACE#41]
When trying to store a password in ecs via `ace store-config-password ews_my_section.password`, ACE spit out an unhelpful error that included all the config sections similar to this:

```bash
[ERROR] DEFAULT
[ERROR] saq
[ERROR] another_config_section
[ERROR] another_config_section_2
.
.
.
etc.
```

After receiving the error, I enabled EWS with `ace integrations enable ews` and the error went away.

A more descriptive error would be helpful--like 'EWS integration is not enabled'--if possible.

**Comment by unixfreak0037** [comment]
Fixed in 276a1e876e4f23854491fbed6a5612a15f11af89
